const TIMEZONES = [
  {value: "Etc/GMT+12", offset: "GMT-12:00", label: "International Date Line West"},
  {value: "America/Adak", offset: "GMT-10:00", label: "Adak (Alaska Aleutian)"},
  {value: "Pacific/Honolulu", offset: "GMT-10:00", label: "Honolulu (Hawaii)"},
  {value: "America/Anchorage", offset: "GMT-09:00", label: "Anchorage (Alaska)"},
  {value: "America/Los_Angeles", offset: "GMT-08:00", label: "Los Angeles (Pacific Time)"},
  {value: "America/Denver", offset: "GMT-07:00", label: "Denver (Mountain Time)"},
  {value: "America/Chicago", offset: "GMT-06:00", label: "Chicago (Central Time)"},
  {value: "America/Guatemala", offset: "GMT-06:00", label: "Guatemala (Central America)"},
  {value: "America/New_York", offset: "GMT-05:00", label: "New York (Eastern Time)"},
  {value: "America/Bogota", offset: "GMT-05:00", label: "Bogotá (Colombia)"},
  {value: "America/Caracas", offset: "GMT-04:00", label: "Caracas (Venezuela)"},
  {value: "America/Halifax", offset: "GMT-04:00", label: "Halifax (Atlantic Time)"},
  {value: "America/Argentina/Buenos_Aires", offset: "GMT-03:00", label: "Buenos Aires"},
  {value: "America/Sao_Paulo", offset: "GMT-03:00", label: "São Paulo"},
  {value: "America/Noronha", offset: "GMT-02:00", label: "Fernando de Noronha"},
  {value: "Atlantic/Azores", offset: "GMT-01:00", label: "Azores"},
  {value: "Atlantic/Cape_Verde", offset: "GMT-01:00", label: "Cape Verde"},
  {value: "Europe/London", offset: "GMT+00:00", label: "London"},
  {value: "Africa/Abidjan", offset: "GMT+00:00", label: "Abidjan (Ghana, Ivory Coast, etc.)"},
  {value: "Atlantic/Reykjavik", offset: "GMT+00:00", label: "Reykjavik (Iceland)"},
  {value: "Europe/Berlin", offset: "GMT+01:00", label: "Berlin (Central European Time)"},
  {value: "Europe/Paris", offset: "GMT+01:00", label: "Paris"},
  {value: "Africa/Lagos", offset: "GMT+01:00", label: "Lagos (West Africa)"},
  {value: "Africa/Johannesburg", offset: "GMT+02:00", label: "Johannesburg (South African Standard Time)"},
  {value: "Europe/Athens", offset: "GMT+02:00", label: "Athens (Eastern European Time)"},
  {value: "Europe/Moscow", offset: "GMT+03:00", label: "Moscow"},
  {value: "Africa/Nairobi", offset: "GMT+03:00", label: "Nairobi (East Africa)"},
  {value: "Asia/Dubai", offset: "GMT+04:00", label: "Dubai"},
  {value: "Asia/Karachi", offset: "GMT+05:00", label: "Karachi"},
  {value: "Asia/Kolkata", offset: "GMT+05:30", label: "New Delhi (India Standard Time)"},
  {value: "Asia/Katmandu", offset: "GMT+05:45", label: "Kathmandu (Nepal)"},
  {value: "Asia/Dhaka", offset: "GMT+06:00", label: "Dhaka"},
  {value: "Asia/Bangkok", offset: "GMT+07:00", label: "Bangkok"},
  {value: "Asia/Hong_Kong", offset: "GMT+08:00", label: "Hong Kong"},
  {value: "Asia/Shanghai", offset: "GMT+08:00", label: "Shanghai (China)"},
  {value: "Australia/Perth", offset: "GMT+08:00", label: "Perth (Western Australia)"},
  {value: "Asia/Tokyo", offset: "GMT+09:00", label: "Tokyo"},
  {value: "Australia/Adelaide", offset: "GMT+09:30", label: "Adelaide (Central Australia)"},
  {value: "Australia/Sydney", offset: "GMT+10:00", label: "Sydney (Eastern Australia)"},
  {value: "Pacific/Guadalcanal", offset: "GMT+11:00", label: "Guadalcanal (Solomon Islands)"},
  {value: "Pacific/Auckland", offset: "GMT+12:00", label: "Auckland (New Zealand)"},
  {value: "Pacific/Fiji", offset: "GMT+12:00", label: "Suva (Fiji)"},
  {value: "Pacific/Chatham", offset: "GMT+12:45", label: "Chatham (New Zealand)"},
  {value: "Pacific/Tongatapu", offset: "GMT+13:00", label: "Nukuʻalofa (Tonga)"}
];

export default TIMEZONES;